In [219]:
import mysql.connector as sql

In [220]:
from  nltk.corpus import stopwords 
from nltk.stem import WordNetLemmatizer
lem=WordNetLemmatizer()

In [221]:
import nltk

In [222]:
import pandas as pd

db_connection = sql.connect(host='sl-aus-syd-1-portal.2.dblayer.com',port=17099, database='FAQ', user='admin', password='VRIXEQIHFTURGYYN')

In [223]:
df = pd.read_sql('SELECT * FROM tbl_FAQ', con=db_connection)

In [224]:
df

     id                                        question
0     1                                           hello
1     8                                              Hi
2    15                                              Hi
3    22                                              Hi
4    29                                              Hi
5    36                                              Hi
6    43                                              Hi
7    50                                              Hi
8    57                                              Hi
9    64                                           hello
10   71                                              Hi
11   78                        May I know about Travel?
12   85                                           hello
13   92                                              Hi
14   99  Could you please tell me about accommodation ?
15  106       Could you please let me know about team ?
16  113            Can I know about team participation?
17  120                                           hello
18  127                                              Hi
19  134                                           hello
20  141                                              Hi
21  148                    May I know about some travel
22  155                                           hello
23  162                                              hi
24  169                 May I know about Accommodation?
25  176                                           hello
26  183                                              Hi
27  190             May I know about the accommodation?
28  197                                           hello
29  204                                           hello
30  211                                           hello
31  218                                              Hi
32  225                                   How are you ?
33  232                    May I know about Hackathon ?
34  239                                           hello
35  246                                           hello

In [225]:
df["question_trans"]=df["question"].str.lower().str.split()

In [183]:
df

,id,question,question_trans
0,1,hello,[hello]
1,8,Hi,[hi]
2,15,Hi,[hi]
3,22,Hi,[hi]
4,29,Hi,[hi]
5,36,Hi,[hi]
6,43,Hi,[hi]
7,50,Hi,[hi]
8,57,Hi,[hi]
9,64,hello,[hello]
10,71,Hi,[hi]
11,78,May I know about Travel?,"[may, i, know, about, travel?]"
12,85,hello,[hello]
13,92,Hi,[hi]
14,99,Could you please tell me about accommodation ?,"[could, you, please, tell, me, about, accommod..."
15,106,Could you please let me know about team ?,"[could, you, please, let, me, know, about, tea..."
16,113,Can I know about team participation?,"[can, i, know, about, team, participation?]"
17,120,hello,[hello]
18,127,Hi,[hi]
19,134,hello,[hello]
20,141,Hi,[hi]
21,148,May I know about some travel,"[may, i, know, about, some, travel]"
22,155,hello,[hello]
23,162,hi,[hi]
24,169,May I know about Accommodation?,"[may, i, know, about, accommodation?]"
25,176,hello,[hello]
26,183,Hi,[hi]
27,190,May I know about the accommodation?,"[may, i, know, about, the, accommodation?]"
28,197,hello,[hello]
29,204,hello,[hello]
30,211,hello,[hello]
31,218,Hi,[hi]
32,225,How are you ?,"[how, are, you, ?]"
33,232,May I know about Hackathon ?,"[may, i, know, about, hackathon, ?]"
34,239,hello,[hello]
35,246,hello,[hello]

In [226]:
stop=stopwords.words("english")

In [227]:
df["question_trans"]=df["question_trans"].apply(lambda x:[lem.lemmatize(item) for item in x if item not in stop])

In [228]:
df["question_trans"]=df["question_trans"].apply(lambda x :" ".join(x))

In [229]:
df["question_trans_noun"]=df["question_trans"].apply(lambda x :[item for item in nltk.word_tokenize(x) ] )

In [230]:
df["question_trans_noun"]=df["question_trans_noun"].apply(lambda x:[nltk.pos_tag(x) for item in x])

In [231]:
df

,id,question,question_trans,question_trans_noun
0,1,hello,hello,"[[(hello, NN)]]"
1,8,Hi,hi,"[[(hi, NN)]]"
2,15,Hi,hi,"[[(hi, NN)]]"
3,22,Hi,hi,"[[(hi, NN)]]"
4,29,Hi,hi,"[[(hi, NN)]]"
5,36,Hi,hi,"[[(hi, NN)]]"
6,43,Hi,hi,"[[(hi, NN)]]"
7,50,Hi,hi,"[[(hi, NN)]]"
8,57,Hi,hi,"[[(hi, NN)]]"
9,64,hello,hello,"[[(hello, NN)]]"
10,71,Hi,hi,"[[(hi, NN)]]"
11,78,May I know about Travel?,may know travel?,"[[(may, MD), (know, VB), (travel, NN), (?, .)]..."
12,85,hello,hello,"[[(hello, NN)]]"
13,92,Hi,hi,"[[(hi, NN)]]"
14,99,Could you please tell me about accommodation ?,could please tell accommodation ?,"[[(could, MD), (please, VB), (tell, VB), (acco..."
15,106,Could you please let me know about team ?,could please let know team ?,"[[(could, MD), (please, VB), (let, VB), (know,..."
16,113,Can I know about team participation?,know team participation?,"[[(know, VB), (team, NN), (participation, NN),..."
17,120,hello,hello,"[[(hello, NN)]]"
18,127,Hi,hi,"[[(hi, NN)]]"
19,134,hello,hello,"[[(hello, NN)]]"
20,141,Hi,hi,"[[(hi, NN)]]"
21,148,May I know about some travel,may know travel,"[[(may, MD), (know, VB), (travel, NN)], [(may,..."
22,155,hello,hello,"[[(hello, NN)]]"
23,162,hi,hi,"[[(hi, NN)]]"
24,169,May I know about Accommodation?,may know accommodation?,"[[(may, MD), (know, VB), (accommodation, NN), ..."
25,176,hello,hello,"[[(hello, NN)]]"
26,183,Hi,hi,"[[(hi, NN)]]"
27,190,May I know about the accommodation?,may know accommodation?,"[[(may, MD), (know, VB), (accommodation, NN), ..."
28,197,hello,hello,"[[(hello, NN)]]"
29,204,hello,hello,"[[(hello, NN)]]"
30,211,hello,hello,"[[(hello, NN)]]"
31,218,Hi,hi,"[[(hi, NN)]]"
32,225,How are you ?,?,"[[(?, .)]]"
33,232,May I know about Hackathon ?,may know hackathon ?,"[[(may, MD), (know, VB), (hackathon, NN), (?, ..."
34,239,hello,hello,"[[(hello, NN)]]"
35,246,hello,hello,"[[(hello, NN)]]"

In [232]:


df["questions_noun_filter"]=df["question_trans_noun"].apply(lambda x:[item[i][0]for item in x for i in range(len(x[0])) if item[i][1]=="NN" ])

In [233]:
df["questions_noun_filter"]=df["questions_noun_filter"].apply(lambda x:[list(set(x))])

In [240]:
df["questions_noun_filter"]=df["questions_noun_filter"].apply(lambda x:(x[0]))